# Generated by Django 6.1.1 on 2026-09-07 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('members', models.ManyToManyField(blank=True, related_name='households', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChoreTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('default_assignee', models.CharField(blank=True, choices=[('partner_a', 'Partner A'), ('partner_b', 'Partner B')], default='', max_length=16)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='chores.household')),
            ],
        ),
        migrations.CreateModel(
            name='WeekPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='week_plans', to='chores.household')),
            ],
        ),
        migrations.CreateModel(
            name='ChoreInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('assignee', models.CharField(choices=[('partner_a', 'Partner A'), ('partner_b', 'Partner B'), ('either', 'Either')], max_length=16)),
                ('complete', models.BooleanField(default=False)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='chores.choretemplate')),
                ('week_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chores', to='chores.weekplan')),
            ],
        ),
        migrations.AddConstraint(
            model_name='weekplan',
            constraint=models.UniqueConstraint(fields=('household', 'week_start'), name='chores_unique_week_plan_per_household'),
        ),
        migrations.AddConstraint(
            model_name='choreinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('template__isnull', False)), fields=('week_plan', 'template'), name='chores_unique_template_instance_per_week'),
        ),
        migrations.AddConstraint(
            model_name='choreinstance',
            constraint=models.UniqueConstraint(condition=models.Q(('template__isnull', True)), fields=('week_plan', 'title', 'date'), name='chores_unique_one_off_instance_per_week'),
        ),
    ]
